services:
  - type: web
    name: NotSoSimpleCalculator
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    rootDirectory: .
    buildCommand: ''
    startCommand: ''
    branch: main
    envVars: []
